-------------------------------------------------------------------------------
Test set: BDVoluntarios_ESTest
-------------------------------------------------------------------------------
Tests run: 57, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.842 sec <<< FAILURE!
test26(BDVoluntarios_ESTest)  Time elapsed: 0.017 sec  <<< ERROR!
java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.containsKey(TreeMap.java:232)
	at java.util.TreeSet.contains(TreeSet.java:234)
	at BDVoluntarios.existeCodigo(BDVoluntarios.java:75)
	at BDVoluntarios_ESTest.test26(BDVoluntarios_ESTest.java:5032)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

